# Generated by Django 5.2.7 on 2025-11-01 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên thư mục')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'Thư mục',
                'verbose_name_plural': 'Thư mục',
                'db_table': 'lasotuvi_folder',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SavedLaSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên lá số')),
                ('hoten', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('ngaysinh', models.IntegerField(verbose_name='Ngày sinh')),
                ('thangsinh', models.IntegerField(verbose_name='Tháng sinh')),
                ('namsinh', models.IntegerField(verbose_name='Năm sinh')),
                ('giosinh', models.IntegerField(verbose_name='Giờ sinh')),
                ('gioitinh', models.CharField(max_length=10, verbose_name='Giới tính')),
                ('amlich', models.BooleanField(default=False, verbose_name='Âm lịch')),
                ('muigio', models.IntegerField(default=7, verbose_name='Múi giờ')),
                ('namxem', models.IntegerField(blank=True, null=True, verbose_name='Năm xem')),
                ('chart_data', models.JSONField(help_text='JSON chứa thienBan và thapNhiCung', verbose_name='Dữ liệu lá số')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Yêu thích')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lasos', to='tuvi.folder', verbose_name='Thư mục')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lasos', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sở hữu')),
            ],
            options={
                'verbose_name': 'Lá số đã lưu',
                'verbose_name_plural': 'Lá số đã lưu',
                'db_table': 'lasotuvi_saved_laso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='lasotuvi_sa_created_eaf784_idx'), models.Index(fields=['is_favorite'], name='lasotuvi_sa_is_favo_25f334_idx')],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
