# Generated by Django 5.2.7 on 2025-10-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuvi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlaso',
            name='namxem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm xem'),
        ),
        migrations.AlterField(
            model_name='savedlaso',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lasos', to='tuvi.folder', verbose_name='Thư mục'),
        ),
    ]
